on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun i
      - run: bun run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8da37f2c68005226e55dffb2ffc7664b
          projectName: blog
          directory: public/build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
